### PR TITLE
(Feature) Separate contract and metadata into files (.sol & .txt) and zip

### LINKED ISSUE #269: New format of downloaded file with metadata on Step 4
Problem A:
At the moment, all files with contracts and metadata have the same name for all networks. When a user creates a crowdsale we download "contractinfo.txt" file on the host.
It results of having files like `contractinfo (10).txt`

Proposal:
- change file to zip file with sol and metadata files inside

`icowizard_%network name or id for unknown network%token.zip`

e.g.
```
icowizard_kovan_0x2c57E1E3AD53F0b971422696c1470cEB84F83B1B.zip
icowizard_mainnet_0xca9B0753E2Ea13d7bBE0e90516Bcf940A275eFA8.zip
```

Problem B:
- it's hard to copy and paste from txt file
- it's hard to auditors to understand file structure

Solution:

Each file will have all created contracts named by contract name with _ and number as a number of tier
e.g. 
```
SafeMathLibExt.sol
MintedTokenCappedCrowdsaleExt_1.sol
MintedTokenCappedCrowdsaleExt_2.sol
CrowdsaleTokenExt.sol
FlatPricingExt_1.sol
FlatPricingExt_2.sol
NullFinalizeAgentExt.sol
ReservedTokensFinalizeAgent.sol
```

and metadata (ABI, Constructor, etc.)
```
SafeMathLibExt.txt
MintedTokenCappedCrowdsaleExt_1.txt
MintedTokenCappedCrowdsaleExt_2.txt
CrowdsaleTokenExt.txt
FlatPricingExt_1.txt
FlatPricingExt_2.txt
NullFinalizeAgentExt.txt
ReservedTokensFinalizeAgent.txt
```

### PR DESCRIPTION
**Pull request by fernandomg**
Closes #269.

- Separates contracts from metadata
- Prefixes with a unique number filenames
- Suffixes metadata and contracts that when there's more than one Tier

For 3 Tiers, the zip file content will be:
```
001_SafeMathLibExt.sol
002_SafeMathLibExt.txt
003_MintedTokenCappedCrowdsaleExt.sol
004_MintedTokenCappedCrowdsaleExt.txt
005_FlatPricingExt_1.sol
006_FlatPricingExt_1.txt
007_FlatPricingExt_2.sol
008_FlatPricingExt_2.txt
009_FlatPricingExt_3.sol
010_FlatPricingExt_3.txt
011_NullFinalizeAgentExt.sol
012_NullFinalizeAgentExt.txt
013_ReservedTokensFinalizeAgent_1.sol
014_ReservedTokensFinalizeAgent_1.txt
015_ReservedTokensFinalizeAgent_2.sol
016_ReservedTokensFinalizeAgent_2.txt
017_ReservedTokensFinalizeAgent_3.sol
018_ReservedTokensFinalizeAgent_3.txt
019_CrowdsaleTokenExt_1.sol
020_CrowdsaleTokenExt_1.txt
021_CrowdsaleTokenExt_2.sol
022_CrowdsaleTokenExt_2.txt
023_CrowdsaleTokenExt_3.sol
024_CrowdsaleTokenExt_3.txt
```

### CODE REVIEW

**Comment by igorbarinov** [comment]
@vbaranov @15chrjef it would be great if you can review it asap, we need this for the audit of our contracts.
@vbaranov please sync it with the bridge version after reviewing

**Comment by fernandomg** [comment]
@vbaranov as it's implemented right now, in the `state.contracts.nullFinalizeAgent` object, there's no `addr` nor

**Comment by vbaranov** [comment]
@fernandomg Yes, for now all finalizeAgent (null and the last) addresses are in this array `state.contracts.finalizeAgent.addr`. And all ABI encoded constructor parameters for all finalizeAgents (null and the last) are in this array `state.contracts.finalizeAgent.abiConstructor`.

>Shall I move the n-1 addr and abiConstructor elements from state.contracts.finalizeAgent into the state.contracts.nullFinalizeAgent so the state reflects what's gonna be in the zip file?

Ideally, yes. I think so. But if it won't break other functionality, that depends on array of `finalizeAgent` addresses.
 
Btw, I made some updates to this branch `separate-files-and-zip`. Please, make pull.

**Comment by fernandomg** [comment]
@vbaranov Should I keep the "fpr Tier x" in the `finalizeAgent` metadata titles?

i.e.:
**1-tier**
```
Finalize agent contract address for Tier 1: 0xCdE...
[...]
****Finalize agent contract ABI encoded constructor arguments for Tier 1:**** 
```

**N-tiers**
```
Finalize agent contract address for Tier N: 0xCdE...
[...]
****Finalize agent contract ABI encoded constructor arguments for Tier N:**** 
```

**Comment by vbaranov** [comment]
@fernandomg right. And for [1:n-1] it will be `nullFinalizeAgent` with ABI and ABI encoded constructor arguments for it and for the last n tier it will be `ReservedTokensFinalizeAgent` with ABI and ABI encoded constructor arguments for it.
If n = 1, it will be only `ReservedTokensFinalizeAgent` with ABI and ABI encoded constructor arguments for it.

**Comment by fernandomg** [comment]
@vbaranov @15chrjef changes done. 

- `NullFinalizeToken` will exist only when there's more than one tier
- `ReservedTokensFinalizeAgent` is generated only once
 - if there's more than one tier, it will have the information for the last tier.

**Pull request merged**
