### PR TITLE
(Fix) Blank screen when MetaMask is not installed

### LINKED ISSUE #386: (Bug) White screen if metamask is not installed
Found this problem here
https://forum.oracles.org/t/ico-wizard-down/358/15?u=igorbarinov
Tried to reproduce it in Chrome incognito mode. Here is the result

### Which network did you use? (Mainnet, Kovan, Rinkeby, etc.)

No metamask installed

### If you were able to create it, what is the URL of your crowdsale?

https://wizard.oracles.org/invest?addr=0x164094E5C47EE28583F2FE9c10b2153a167e567a&networkID=1

### Do you have screenshots showing the problem?

image

### Do you see errors in the dev console? If yes, please include a screenshot

```
blockchainHelpers.js:42 Please use a web3 browser
o @ blockchainHelpers.js:42
Web3Store.js:13 Uncaught TypeError: Cannot read property 'eth' of undefined
    at Web3Store.js:13
    at o (blockchainHelpers.js:48)
    at new e (Web3Store.js:11)
    at Object.<anonymous> (Web3Store.js:21)
    at t (bootstrap 1c16a57d86d7d2176ef5:19)
    at Object.<anonymous> (index.js:10)
    at t (bootstrap 1c16a57d86d7d2176ef5:19)
    at Object.<anonymous> (utils.js:2)
    at t (bootstrap 1c16a57d86d7d2176ef5:19)
    at Object.<anonymous> (microservices.js:1)
    at t (bootstrap 1c16a57d86d7d2176ef5:19)
    at Object.<anonymous> (blockchainHelpers.js:3)
    at t (bootstrap 1c16a57d86d7d2176ef5:19)
    at Object.<anonymous> (index.js:3)
    at t (bootstrap 1c16a57d86d7d2176ef5:19)
    at Object.<anonymous> (main.651435e3.js:52190)
    at t (bootstrap 1c16a57d86d7d2176ef5:19)
    at Object.<anonymous> (App.js:3)
    at t (bootstrap 1c16a57d86d7d2176ef5:19)
    at Object.<anonymous> (index.js:3)
    at t (bootstrap 1c16a57d86d7d2176ef5:19)
    at Object.<anonymous> (main.651435e3.js:140837)
```

### PR DESCRIPTION
**Pull request by fvictorio**
Closes #386.

### CODE REVIEW

**Comment by igorbarinov** [comment]
Can we delete `no-mestamask` branch?

**Comment by fvictorio** [comment]
Sure, I deleted it.

**Comment by linahoo** [comment]
i have some problem in step 3 
TypeError: Cannot read property 'addr' of undefined
new stepThree
C:/Users/ahoo_lin/ICO/wiz/src/components/stepThree/index.js:42
  39 | super(props);
  40 | const { contractStore, crowdsaleBlockListStore, tierStore } = props;
  41 | window.scrollTo(0, 0);
> 42 | if (contractStore.crowdsale.addr.length > 0) {
  43 |   contractStore.setContractProperty("pricingStrategy", "addr", []);
  44 |   setExistingContractParams(contractStore.abi, contractStore.addr[0], contractStore.setContractProperty);

**Comment by linahoo** [comment]
[
step 3 error
](url)

**Comment by fvictorio** [comment]
Hi @linahoo. Please create a new issue if you have a question.

That error happens when you reload the page in the third step. You need to start over (go to `localhost:3000/`).

**Pull request merged**
