### PR TITLE
(Refactor) Mobx state management

### PR DESCRIPTION
**Pull request by 15chrjef**
***This is a huge commit that will require significant time dedicated to testing and resolving merge conflicts. It is a work in progress and is planned to be updated often until it is finally merged in.***

*High Level Changes*
- Mobx state management
- removal of component state management
- some small cleanup and refactoring where appropriate
- pricing strategy integrated into the relevant information of its corresponding tier

*More Detailed Changes*

Ejected create-react-app for access to babel, which allows us to use decorators.
Babel file was based upon current mobx documentation.
Updated naming convention of all stores. Each store's name should ideally have 'store' within it to draw less confusion when importing stores into components.
I updated the initialized item name and the class itself.
Added an index.js files for all stores, and imported the stores into App.js. Stores are passed into the Provider method of 'mobx-react'.
Added a build_scripts folder that will hold build, start, and test files.
Things to test

Ensure that the ejection from create-react-app will not obstruct our build process.
Check to see that the provider component has access to the stores. This can be easily done through react-devtools, by checking that the props contain an object of stores.

### CODE REVIEW

**Comment by vbaranov** [comment]
@15chrjef use this [package.json](https://github.com/vbaranov/ico-wizard/blob/mobx/package.json) for Mobx PR

**Comment by vbaranov** [comment]
@15chrjef you can merge [my PR](https://github.com/15chrjef/ico-wizard/pull/5/files) to your branch to make deployment stage of Wizard working

**Comment by 15chrjef** [comment]
Thanks @vbaranov. It works with the crowdsale through Kovan on the Invest and crowdsale page.

**Comment by vbaranov** [comment]
@15chrjef  one bug still exists: ` for [Tier name]: ` is lost.

From the downloaded at step 4 file: 
1. Crowdsale contract address0xB1FF1C4D7BfaF3aeFe4eF1e3aB604b7F2b28410f -> Crowdsale contract address for [Tier name]: 0xB1FF1C4D7BfaF3aeFe4eF1e3aB604b7F2b28410f
2. Pricing strategy contract address0x3D8E0Fa030a44e77F9C4738AEE843752d79bA1FD -> Pricing strategy contract address for [Tier name]: 0x3D8E0Fa030a44e77F9C4738AEE843752d79bA1FD
3. Finalize agent contract address0x2Aeb492CEEA0aF88E1EAf681f0578886eBaA7372 -> Finalize agent contract address for [Tier name]: 0x2Aeb492CEEA0aF88E1EAf681f0578886eBaA7372

**Comment by 15chrjef** [comment]
Where do you get these errors? What prompts it?

**Comment by vbaranov** [comment]
@15chrjef It is from downloaded file at step 4. Try to download and compare with that from master branch

**Comment by fvictorio** [comment]
I looked into this PR and here's what I thing we should do:

1. Merge the other 3 open PRs first, otherwise is going to be extra hard. #199 and #358 are ready IMO; #341 depends on #199 and needs a proper review when this is merged, but it's only view layer stuff so it shouldn't take long. Any non-critical problems with those PRs should go to open issues and be taken care of _after_ this MobX PR is merged.
2. Solve the conflicting files very carefully. Probably @15chrjef is the best person to do it, but if he's busy, I can give it a try. What I'd do is to use the files with conflicts and re-apply the MobX changes by hand, because several things have changed since the last commit in the merged branch, and because solving each conflict by hand is very error prone.

I think this PR is very important for improving the codebase, and the longer we wait, the harder it will be to do it. If there's nothing of much higher priority, I'd focus our efforts this week in getting this merge out of the way.

**Pull request merged**
