### PR TITLE
(Refactor) Mobx state management

### PR DESCRIPTION
**Pull request by fvictorio**
This is a continuation of #304, with the merge conflicts resolved. I created a new PR because I can't push to @15chrjef repo.

### CODE REVIEW

**Comment by fvictorio** [comment]
I resolved the merge conflicts and fixed several runtime errors that appeared because of the merge. Next I'll try to fix the bugs that arose.

**Comment by fvictorio** [comment]
This should be ready for test and review. @fernandomg helped me with the merge conflicts and the bugs that appeared, so I didn't add him as a reviewer.

**Comment by vbaranov** [comment]
Example of incorrect downloaded file
[icowizard_Kovan_0x1341BdB83D19F6Acfc806f79E02aD9aA83eDf4d9.zip](https://github.com/oraclesorg/ico-wizard/files/1498734/icowizard_Kovan_0x1341BdB83D19F6Acfc806f79E02aD9aA83eDf4d9.zip)

**Comment by fvictorio** [comment]
We'll start working on the first two points.

Address validation was reverted in master, so I'd say we do that in another PR after this one is merged.

Crowdsale and invest pages were working last time I checked, I used them a lot while testing this. Can you attach an screenshot or video showing how it's broken?

**Comment by vbaranov** [comment]
@fvictorio sure, https://drive.google.com/file/d/1qMlyrvvShPWfPPMxu5EoTjCmTIdr9L6V/view

**Comment by fvictorio** [comment]
@vbaranov Kovan doesn't seem to support Byzantium yet: https://github.com/paritytech/parity/issues/7080

**Comment by vbaranov** [comment]
@fvictorio check, please, the main link of wizard. It works with Kovan. And we've already added Byzantium support to the master branch here https://github.com/oraclesorg/ico-wizard/pull/364

**Comment by igorbarinov** [comment]
Kovan will be upgraded to Byzantium soon. Although, there are other Blockchains which are Ethereum compatible and users could use it Wizard.

**Comment by fernandomg** [comment]
Fixed files downloaded.

Something to notice, in master as in this branch Crowdsale info (rate, start time and end time) **is the same**, despite the different tiers.

Let me know if you want me to fix it ASAP in a different issue.

**Comment by vbaranov** [comment]
@fernandomg yes, it'll be nice fix.

**Comment by fernandomg** [comment]
#369 will be fixed when this PR got merged into master

**Comment by fvictorio** [comment]
Is there something pending here?

**Comment by vbaranov** [comment]
@fvictorio I'm working on review of it

**Comment by vbaranov** [comment]
@fvictorio 
1. Goal in ETH is empty. You can check here `1. /crowdsale?addr=0xae6bD63A5cfE760710aD063C530D12B91650a8e5&networkID=42`
image 2017-11-24 14-47-37

I am reviewing further

**Comment by vbaranov** [comment]
@fvictorio @fernandomg 
2. 
image 2017-11-24 16-48-16

3. Contributors is not empty here: https://wizard.oracles.org/crowdsale?addr=0xa3f54827dE7AC856762F77A0A9701548170e07D6&networkID=1
But from this branch amount of contributors is 0 from this branch.

**Comment by igorbarinov** [comment]
@fvictorio @fernandomg great job.
- I think we should add a document to Wiki with the state structure and how-to for new developers
- let's start release policy with this important and large PR. How do you feel about release 0.1?

**Comment by fvictorio** [comment]
0.1 sounds good.

I'll add some documentation in the wiki for new developers, but I don't think documenting the state structure is worth it: it's going to get old fast, and the MobX stores seem pretty self-documenting. What do you think?

**Comment by igorbarinov** [comment]
If you can document basic ideas of our state to new developers it would be great
I agree with you about state structure if it will be old soon

**Comment by vbaranov** [comment]
I agree with documenting of structure. Day will come, when we'll forgot, where some properties for wizard is stored, if we won't describe it.

**Comment by fvictorio** [comment]
I added a page to the wiki: https://github.com/oraclesorg/ico-wizard/wiki/Source-code-structure

I didn't describe all stores because I think some of them should be replaced with local state.

**Comment by igorbarinov** [comment]
@fvictorio could we deploy it on stage server? At the moment the way we did it is to merge a PR into `stage` branch?

Do you have any other ideas for staging?

**Comment by fvictorio** [comment]
No, that sounds perfect. I'll merge it on the `stage` branch.

**Comment by fvictorio** [comment]
Done, it is in the stage server now. I am testing it there.

**Comment by igorbarinov** [comment]
@fvictorio thank you, will test too

@vbaranov Viktor, btw what was the idea behind syncing to branches using PRs? E.g. https://github.com/oraclesorg/ico-wizard/pull/368 
If there is no special reason let's sync branches without PRs.

**Comment by fvictorio** [comment]
It seems to be working fine. I tested crowdsales with token reservation, multiple tiers, whitelisting.

**Comment by fvictorio** [comment]
Hi, what's the next step here? Do we leave it in stage some time more for testing or can we merge it into master?

**Comment by igorbarinov** [comment]
Congrats everyone on PR merge!

@fvictorio could you please create a tag and release the source code in it with brief description of MobX changes.

**Comment by fvictorio** [comment]
Sure!

**Pull request merged**
