### PR TITLE
(Feature) Callbacks to promises

### LINKED ISSUE #318: (Suggestion): Replace callbacks with promises
This will probably be a big refactor, but I think the impact in maintainability is huge.

Code like this:

```js
setLastCrowdsaleRecursive(0, web3, contracts.pricingStrategy.abi, contracts.pricingStrategy.addr, contracts.crowdsale.addr.slice(-1)[0], 42982, (err) => {
  if (err) return this.hideLoader();
  setReservedTokensListMultiple(web3, contracts.token.abi, contracts.token.addr, this.state.token, (err) => {
    if (err) return this.hideLoader();
    updateJoinedCrowdsalesRecursive(0, web3, contracts.crowdsale.abi, contracts.crowdsale.addr, (err) => {
      if (err) return this.hideLoader();
      setMintAgentRecursive(0, web3, contracts.token.abi, contracts.token.addr, contracts.crowdsale.addr, 68425, (err) => {
        if (err) return this.hideLoader();
        setMintAgentRecursive(0, web3, contracts.token.abi, contracts.token.addr, contracts.finalizeAgent.addr, 68425, (err) => {
          if (err) return this.hideLoader();
          addWhiteListRecursive(0, web3, this.state.crowdsale, this.state.token, contracts.crowdsale.abi, contracts.crowdsale.addr, (err) => {
            if (err) return this.hideLoader();
            setFinalizeAgentRecursive(0, web3, contracts.crowdsale.abi, contracts.crowdsale.addr, contracts.finalizeAgent.addr, 68622, (err) => {
              if (err) return this.hideLoader();
              setReleaseAgentRecursive(0, web3, contracts.token.abi, contracts.token.addr, contracts.finalizeAgent.addr, 65905, (err) => {
                transferOwnership(web3, this.state.contracts.token.abi, contracts.token.addr, this.state.crowdsale[0].walletAddress, 46699, (err) => {
                  if (err) return this.hideLoader();
                  this.hideLoader();
                });
              });
            });
          });
        });
      });
    });
  });
});
```

would be replaced by:

```js
setLastCrowdsaleRecursive(0, web3, contracts.pricingStrategy.abi, contracts.pricingStrategy.addr, contracts.crowdsale.addr.slice(-1)[0], 42982)
  .then(() => setReservedTokensListMultiple(web3, contracts.token.abi, contracts.token.addr, this.state.token))
  .then(() => updateJoinedCrowdsalesRecursive(0, web3, contracts.crowdsale.abi, contracts.crowdsale.addr))
  .then(() => setMintAgentRecursive(0, web3, contracts.token.abi, contracts.token.addr, contracts.crowdsale.addr, 68425))
  .then(() => setMintAgentRecursive(0, web3, contracts.token.abi, contracts.token.addr, contracts.finalizeAgent.addr, 68425))
  .then(() => addWhiteListRecursive(0, web3, this.state.crowdsale, this.state.token, contracts.crowdsale.abi, contracts.crowdsale.addr))
  .then(() => setFinalizeAgentRecursive(0, web3, contracts.crowdsale.abi, contracts.crowdsale.addr, contracts.finalizeAgent.addr, 68622))
  .then(() => setReleaseAgentRecursive(0, web3, contracts.token.abi, contracts.token.addr, contracts.finalizeAgent.addr, 65905))
  .then(() => transferOwnership(web3, this.state.contracts.token.abi, contracts.token.addr, this.state.crowdsale[0].walletAddress, 46699))
  .then(() => this.hideLoader())
  .catch(() => this.hideLoader())
```

### PR DESCRIPTION
**Pull request by fernandomg**
Closes #318 

Mostly of the code was replaced with promises. There are still parts in the utility files that keeps using callbacks.

Tested with **testrpc**, with and without `--blocktime` flag, and in **rinkeby** test net.

### CODE REVIEW

**Comment by vbaranov** [comment]
@fernandomg could I review, or PR will be amended?

**Comment by fernandomg** [comment]
@vbaranov I'm about to push a few modifications and that's all, give me a couple minutes

**Comment by fernandomg** [comment]
@vbaranov ready, please review. Thank you!

**Comment by vbaranov** [comment]
I'll test today with another public chain. Maybe, the problem was caused by Kovan itself: http://authorities.kovan.network/.
@fernandomg I'll let you know

**Comment by fvictorio** [comment]
Yes, Kovan seems to be acting weird, not sure why.

**Comment by fernandomg** [comment]
@vbaranov fix done, thank you for the feedback!

**Comment by fvictorio** [comment]
@vbaranov can we merge this?

**Comment by vbaranov** [comment]
@fvictorio  yes, no issues for me now. I'll merge.

**Pull request merged**
