### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by blockarray**
added: blockarray to project list using ICO wizard

thanks guys

### CODE REVIEW

**Comment by blockarray** [comment]
thank you

**Comment by igorbarinov** [comment]
@blockarray why you closed it?

**Comment by blockarray** [comment]
didn't even notice - sorry

**Comment by fvictorio** [comment]
I see that the "Projects created with ICO Wizard" section was moved to the wiki (https://github.com/oraclesorg/ico-wizard/wiki/ICO-Wizard-Projects).  I added BlockArray there, so this PR is no longer necessary.

**Pull request closed without merging**
