### PR TITLE
Upgrade of web3, bugs in deployContract, UI Fixes, Refactoring

### PR DESCRIPTION
**Pull request by vbaranov**
**Change log:**
1. Migration from web3@0.19.1 to web3@1.0.0-beta.22 (web3.toWei -> web3.utils.toWei, web3.fromWei -> web3.utils.fromWei, web3.isAddress -> web3.utils.isAddress, contract deployment, call of contract methods, sending of tx to contract, web3.eth.accounts -> web3.eth.getAccounts())
2. Callback is fixed for deployContract function in `stepFour\utils` (doubled callback fix)
3. Depreciated code is removed
4. Twitter link is fixed in footer

Joined issue: https://github.com/oraclesorg/ico-wizard/issues/232
Possible joined issue: https://github.com/oraclesorg/ico-wizard/issues/206

Affected 3 end-users at least

### CODE REVIEW

**Comment by igorbarinov** [comment]
I tested it on Stage server and had one issue with an exception in a contract and warning from metamask?
image

I recorded a video with my test, it's in the fifth minute.
https://youtu.be/N5mwzEiD7Tw?t=5m

**Comment by 15chrjef** [comment]
How urgent is this? I would like to minimize the updates to code that touches 'state' until the new state management system is here.

**Comment by vbaranov** [comment]
Fixes from this PR may affect end-users on production to solve their problems. IMHO, it is urgent.

**Comment by igorbarinov** [comment]
I agree, let's merge it :100:

**Comment by vbaranov** [comment]
@15chrjef Thanks. I'll help you with manual merging for your PRs.

**Pull request merged**
